apiVersion: apps/v1
kind: Deployment
metadata:
  name: omke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omke
  template:
    metadata:
      labels:
        app: omke
    spec:
      containers:
      - image: okteto.dev/omke:latest
        name: omke
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "69ccb740-6c4a-4163-bc32-70c508f15084"
        - name: Vless_Path
          value: "/69ccb740-6c4a-4163-bc32-70c508f15084"
        - name: Vmess_UUID
          value: "4d89f01d-1328-4735-a2b6-476c4b8aa2ef"
        - name: Vmess_Path
          value: "/4d89f01d-1328-4735-a2b6-476c4b8aa2ef"
        - name: Share_Path
          value: "/v2link"
